# --- jekyll config ---

# Site settings
title: michael wager | cyber security consultant
email: mail@mwager.de
description: "cyber security consultant"
keywords: "javascript typescript nodejs php software engineering germany augsburg m√ºnchen munich blog freelance fullstack web developer frontend backend security forensics cyber cybersecurity linux hacking container distroless appsec devsecops devops cloud native"
baseurl: ""
url: "https://mwager.de"

# source: ./

# some globals:
street: Lauterlech 39
address: 86152 Augsburg

# Build settings
# markdown: (kramdown or redcarpet?)
markdown: kramdown
permalink: pretty

# custom ...
highlighter: pygments
timezone: Europe/Berlin

# NOTE: github overwrites this to true, so we can use it as "production" env flag:
safe: false

# on mwager.de we use this: (replaced to "prod" by grunt deploy)
env: "dev"

lsi: false

# https://stackoverflow.com/questions/30625044/jekyll-post-not-generated
future: true

# exclude file while running "jekyll build"
# NOTE: .htaccess manually
exclude: [_.*, Gruntfile.js, package.json, README.md, readme.md]
